services:
  # # Frontend
  # poker-frontend:
  #   container_name: poker-frontend
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8086:80"
  # # Backend
  # poker-backend:
  #   container_name: poker-backend
  #   restart: always
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8087:4000"
  #     - "8083:5001"
  #   entrypoint: ["pnpm", "start"]
  #   depends_on:
  #     - poker-mysql
  #     - poker-redis

  # Database
  db:
    image: postgres:17.0
    container_name: postgres_poker_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis service
  poker-redis:
    image: redis:latest
    container_name: poker-redis
    ports:
      - "8082:6379"
    environment:
      - REDIS_PASSWORD=cx34CGDhFuz4XfDjWjBXQa3xzsyQWy
    volumes:
      - poker-redis-data:/data

volumes:
  pgdata:
  poker-redis-data:
